- requirements.txt
- setup.py
- tests/test_connect.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-69
> TNR-69: include amenities

- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-650
Add a new method to the connect sdk that uses the new /v1/unit-amenities-reduced endpoint.
> TNR-650: Add method for unit-amenities-reduced.

- vacasa/connect/connect.py
For polling reservations from Connect for new Housekeeping Service (and future other things)
> Add get_reservations() method

- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-1000
Add support for the new /v1/amenities-groups endpoint in the Connect API.
> TNR-1000: Add support for /v1/amenities-groups.

- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-1047
Make the SDK handle missing host names in pagination links returned by the Connect API.
> TNR-1047: Handle missing host name in page links.

- Pipfile
- Pipfile.lock
- README.md
- requirements.txt
- setup.py
- tests/test_connect.py
- vacasa/connect/connect.py
Also
-converted to pipenv
-added install_requires to setup.py
-converted to pendulum 2+
-removed some unnecessary `if params is None` checks
> TNR-1678: Add /v1/offices endpoint

- Pipfile
- Pipfile.lock
- setup.py
- tests/test_connect.py
- vacasa/connect/connect.py
- Also bump version of `requests` due to CVE-2018-18074
> TNR-1756: Quotes and Reservations

- Pipfile
- Pipfile.lock
- setup.py
- vacasa/connect/connect.py
TNR-1804
Switched from backoff to retry, for gunicorn compatibility within cms ecosytem
> TNR-1804: Switched backoff to retry for gunicorn compatibility

- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-1835
- Make retrying optional in get requests
- Update the quote function so it does not retry
> TNR-1835: Make retry optional.

- setup.py
- vacasa/connect/connect.py
add cvv to reservations endpoint and convert trip_protection into a format that connect recognizes
> TNR-1756: reservations cvv

- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-1904
Add create_blocklist_entry() method to exercise Vacasa's connect API blocklist endpoint.
> Tnr 1904 checkout blocklist

- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-2033
Add a new endpoint that returns unit events. This will enable us to do incremental unit data syncs.
> TNR-2033: Add get_unit_events method.

- vacasa/connect/connect.py
Add the pages endpoint exposed by https://vacasait.atlassian.net/browse/CONNECT-340
Also tweaked the retry logic to turn off retry-by-default on a few endpoints
> add the pages endpoint, tweak some retry logic

- setup.py
- vacasa/connect/connect.py
Add create canceled reservation connect endpoint support.
> TNR-2038-cancel-reservation

- setup.py
- vacasa/connect/connect.py
TNR-2038
Updated version to match tags.
Updated create_blocklist_entry docstring to match standard.
Put support for optional `discount_id` inside create_cancelled_reservation method.
> Tnr 2038 cancel reservation

- vacasa/connect/connect.py
Fix validation issue with adding reservation guests
Also sneak in `initial_payment_amount` because I already had it there.
> TNR-2190: Fix validation issue with adding reservation guests

- vacasa/connect/connect.py
TNR-2216: Added identity check endpoint
> TNR-2216: Added identity check endpoint

- vacasa/connect/connect.py
TNR-2271:
Updated create_blocklist_entry to convert true false to 0 or 1
> TNR-2271: Converted bool to zeor or 1

- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-2282
> TNR-2282:  Add email to cancelled reservations

- vacasa/connect/connect.py
TNR-2271
Fixed issue with optional blocklist
> TNR-2271: Fixed issue with optional blocklist

- vacasa/connect/connect.py
https://vacasa.docs.stoplight.io/identity-checks/postv1identitychecks
> TNR-2271: blocklist_id tweaks

- Pipfile
- Pipfile.lock
- vacasa/connect/__init__.py
- vacasa/connect/connect.py
- vacasa/connect/idp_auth.py
- vacasa/connect/requests_config.py
- vacasa/connect/util.py
https://vacasait.atlassian.net/browse/TNR-2129
Add IdP Auth to connect API
- Also cleaned up some retry logic (hopefully)
> TNR-2129: Add IdP Auth to connect API

- tests/test_connect.py
- tests/test_data.py
- tests/test_expected.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-2459
- Pass the timestamp for when a user agrees to the rental terms through to Connect as the `terms` parameter when creating a reservation
- Make tests pass again
- Fill in some missing docstring args
> TNR-2459: Pass through rental agreement terms.

- README.md
- setup.py
- tests/test_connect.py
- tests/test_data.py
- tests/test_expected.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-2468
- Add two new optional parameters to the `create_reservation` and `create_cancelled_reservation` methods.
- Tidy up some unrelated docstrings
> TNR-2468: Add reservation parameters for currency codes.

- Pipfile
- Pipfile.lock
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-788
https://vacasait.atlassian.net/browse/GROW-842
Adding sdk endpoints for post/get in order to get lists and  create Units, Contracts and Contacts.
Also updated python version to 3.7
> GROW-842: Changes for OGN Units, Contracts, Contacts

- setup.py
- vacasa/connect/connect.py
GROW-871: Forgot `secured_by` property.
> GROW-871: Forgot `secured_by` property.

- setup.py
- vacasa/connect/connect.py
Connect API will auto-create a code if it is not provided.
> GROW-871: Name and Code are no longer required. 

- setup.py
- vacasa/connect/connect.py
Finishing touches on creating contracts, contacts, and units for OLS.
> GROW-851: Create Contracts/Contacts

- setup.py
- vacasa/connect/connect.py
GROW-880: Adding a flag for `send_email` defaulted to False
> GROW-880: Adding `send_email` flag.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-2968
- Switch `get_quote()` to v2 endpoint
- Add changelog
> TNR-2968: Switch to v2 quotes endpoint.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
Added a created_by param that passes the user_id to the create reservation seed endpoint.
> TNR-3180 added user_id param to res seed

- vacasa/connect/connect.py
Adding post for reservation import.
> GROW-933: Adding import reservation for connect

- CHANGELOG.md
- setup.py
Just adding context missed on the previous release.
> Add missing changelog and version bump.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
Found miss match in connect params, and what I was sending connect.
> Changing auto_pay to autopay to match connect params.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-952
Adding languages for creation of contacts.
> GROW-952: Adding languages for connect.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
Adding missing non required parameter phone2
> Adding phone2 to connect middleware, it is not a required parameter.

- CHANGELOG.md
- setup.py
- tests/test_connect.py
- tests/test_data.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-1141
Making Notes/Email not required.
> Changed 2 inputs to be not required anymore. (Email/Notes)

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-3176
Remove the deprecated reservation-seed parameters.
> TNR-3176: Change reservation seed method.

- CHANGELOG.md
- setup.py
- tests/test_data.py
- vacasa/connect/connect.py
- vacasa/connect/util.py
https://vacasait.atlassian.net/browse/TNR-3190
- Subtract 1 day from `departure` param so it accurately reflects the expected `last_night` value.
- Fix broken reservation import test.
> TNR-3190: Fix cancelled reservation departure date.

- vacasa/connect/util.py
TNR-3365: Quietened down tests
> TNR-3365: quietened down tests

- CHANGELOG.md
- setup.py
- vacasa/connect/util.py
> Tnr 3365 reduce error chatter

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
Add calls for contract template versions, forms, channel fee cost sharings, and amendment by notices.
> Add 4 contract calls for Connect API

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-1176
Add get_unit_amenity_properties method for call to Connect API.
> GROW-1176 Add get_unit_amenity_properties method for Connect API

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-1176
Add add_unit_amenity_property and update_unit_amenity_property methods to call Connect API.
> GROW-1176 Add add_unit_amenity_property and update_unit_amenity_property methods

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/GROW-1176
Add add_unit_amenity and update_unit_amenity methods for calls to Connect API.
Update payload structure for and check status in add_unit_amenity_property and update_unit_amenity_property methods.
> Grow 1176 add unit amenities and update unit amenity properties

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
###JIRA
https://vacasait.atlassian.net/browse/UJM-1243
###Description
Update unit amenity property to idamenities_properties for Connect API. 
Connect API documentation currently has idamenities_property, which needs to be updated.
> UJM-1243 update unit amenity property to idamenities_properties

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-3617
Add the new `fsc` parameter to the `create_reservation()` method.
> TNR-3617: Add fsc param to create_reservation().

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
facilitate reservation cancelling, optionally issuing FSCs
> Added `cancel_reservation_preview()` and `cancel_reservation_apply()`

- .github/pull_request_template.md
- README.md
Adding a PR template with reminders to update the changelog and version. Also added those notes to the readme.
> Add PR template and update readme.

- CHANGELOG.md
- setup.py
> fix the release version

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
NA
Fix reservation buffer methods
> Fix reservation buffer methods

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-150
Unit blocks endpoints identation was fixed
> TRAP-150 | Unit Block Endpoints

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/
Add reason ID in create_unit_reservation_buffer
> Add reason ID

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-191
Fix reason ID name
> TRAP-191 Fix reason ID name

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-191
fix dict in update reservation buffer
> TRAP-191 Fix update reservation buffer

- CHANGELOG.md
- setup.py
n/a
- Migrate from distutils -> setuptools
> Testing setuptools instead

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/UJM-1453
Add get login by email address method for new login endpoint
> UJM-1453 Add get login by email address method

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/UJM-1501
Remove params that are None so they don't trash current data.
> UJM-1501: Remove params that are None so they don't trash current data.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-541
Added Delete method for unit reservation buffer
> TRAP-541 | Add delete client method

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-565
Get Post and Patch methods were added for accounting entity units table.
> TRAP-565 | Add accounting entity methods

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-565
AE method params were fixed.
> TRAP-565 | Fix AE methods

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/UJM-1432
Updated parameters for update_contact_finances
> UJM-1432: Updating Tax Information

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/UJM-1521
- Adde `secured_by` parameter to `create_contract` method.
> UJM-1521 Added secured_by parameter to create_contract method

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TNR-4166
Propagate discount_id when creating res seeds
> TNR-4166: Propagate discount_id when creating res seeds

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/UJM-1521
On `create_contract` add `secured_by` only if not none.
> UJM-1521 Add secured_by if not None

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-1229
adding get_acqquisition
> TRAP-1229 adding get_acquisition

- CHANGELOG.md
- setup.py
https://vacasait.atlassian.net/browse/RT-393
Updated the `install_requires` section of `setup.py` to match current version in the `Pipfile.lock`.
> RT-393: Update install_requires versions in setup.py.

- CHANGELOG.md
- Pipfile.lock
- setup.py
N/A
This updates our python dependencies in response to Dependabot alerts that have been raised.
> Update python dependencies.

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TRAP-2056
Adding required filter to amenities
> TRAP-2056 Adding required filter to amenities

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TPD-5755
Adds support for GET /tickets and GET/tickets/{ID}
> TPD-5755: Add support for retrieving tickets

- CHANGELOG.md
- setup.py
- tests/test_connect.py
- tests/test_data.py
- tests/test_expected.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TPD-5691
add update and post to tickets in Connect SDK
> TPD-5691 Add update and post to tickets

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/PP-668
* add optional `user_agent` client arg to specify the `User-Agent` header string
> PP-668: Add User-Agent Header

- CHANGELOG.md
- setup.py
> Updating tag version

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TPD-5754
Update the get tickets functions to allow for an includes for comments.
> TPD-5754 Update get tickets to easily include comments

- CHANGELOG.md
- setup.py
- vacasa/connect/connect.py
https://vacasait.atlassian.net/browse/TPD-5922
Support posting maintenance ticket comments through Connect.
> TPD-5922 Support posting maintenance ticket comments through Connect
